#ifndef CONFIG_H
#define CONFIG_H

#define UART_BAUDRATE 9600
#define UART_BUFFERING_SIZE 16
#define VT_INPUT_BUFFER_SIZE 32
#define VT_OUTPUT_ESC_SEQ_SIZE 8
#define ENABLE_UART_DOUBLE_SPEEN 1
#define VT_PROMPT "> "
#define SHELL_TOKENS_MAX 10

#endif//CONFIG_H
